### ISSUE TITLE
reverseproxy missing file in git.

### ISSUE THREAD

**Issue by realCedrix** [xuad/docker-contao#2]
Do you want to add this file `docker-compose.yml` to your repo?

```
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_ENV_CERT_PATH}:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
```
